version: "3.9"
services:
  nginx:
    build: "./nginx"
    # volumes : "./nginx/conf:/etc/nginx/"
    restart : "always"
    environment :
      - "TZ=Asia/Seoul"
    ports : 
      - "9001:80"
    volumes:
      - "./nginx/conf/conf.d:/etc/nginx/conf.d"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
    networks : 
      front_end :
        ipv4_address: 172.169.0.2
      back_end :
        ipv4_address: 172.170.0.2
  admin_site:
    build: "./admin_site"
    restart : "always"
    tty : true
    ports:
      - "9002:3000"
    volumes:
        - "./react/source:/var/www"
        - "./share:/var/www/share"
    networks : 
      front_end :
        ipv4_address: 172.169.0.3

  user_site:
    build: "./user_site"
    restart : "always"
    ports:
      - "9003:3000"
    environment :
      - "TZ=Asia/Seoul"
    tty : true
    volumes:
      - "./react/source:/var/www"
      - "./share:/var/www/share"
    networks : 
      front_end :
        ipv4_address: 172.169.0.4
  api:
    build: "./api"
    tty : true
    restart : "always"
    ports:
      - "9004:80"
    volumes:
      - "./api/source:/var/www"
      - "./share:/var/www/share"
    networks :
      back_end :
        ipv4_address: 172.170.0.4
networks:
  front_end:
    ipam:
      driver: default
      config :
       - subnet: 172.169.0.0/16
  back_end:
    ipam:
      driver: default
      config : 
        - subnet: 172.170.0.0/16